#!/usr/bin/env bash

# Code generated by external/generate/teamcity/provider_tests.go; DO NOT EDIT.

set -euo pipefail

go test \
    ./external/acctest/... \
    ./external/attrmap/... \
    ./external/conns/... \
    ./external/create/... \
    ./external/dns/... \
    ./external/enum/... \
    ./external/envvar/... \
    ./external/errs/... \
    ./external/experimental/... \
    ./external/flex/... \
    ./external/framework/... \
    ./external/function/... \
    ./external/generate/... \
    ./external/io/... \
    ./external/json/... \
    ./external/logging/... \
    ./external/maps/... \
    ./external/namevaluesfilters/... \
    ./external/provider/... \
    ./external/reflect/... \
    ./external/retry/... \
    ./external/sdkv2/... \
    ./external/semver/... \
    ./external/slices/... \
    ./external/sweep/... \
    ./external/tags/... \
    ./external/tfresource/... \
    ./external/types/... \
    ./external/vault/... \
    ./external/verify/... \
    ./external/yaml/... \
    -json
